### ISSUE TITLE
Bsd make specifics?

### ISSUE THREAD

**Issue by leenaars** [kristapsdz/kcgi#62] opened 2019-02-25 23:32 UTC
When compiling with GNU Make, I suddenly get an error: Makefile:309: *** missing separator.
Do you know what happens there, and can it be avoided by tweaking the makefile? This did not happen with previous version 0.10.7... and bsd make was not available for me at the time either. Hope this is not a necessary compatibility issue...

**Comment by sammyj85** [comment] 2019-02-26 22:08
GNU Make is no longer supported. You must use BSD make from now (package is probably called bmake, at least on Debian-based systems).

GNUmakefile was removed: https://github.com/kristapsdz/kcgi/commit/eebfeddee4e57df9bfa55d61cbbc69e1e1c01d8c

BSD Makefile was reinstated for simplicity: https://github.com/kristapsdz/kcgi/commit/99d17fc0554f091d4a9f1e4736d78fbb962f16b0

**Comment by leenaars** [comment] 2019-02-26 22:15
I'm on NixOS, which has quite a few make alternatives but not the bsd one for some reason...

**Comment by kristapsdz** [comment] 2019-07-05 14:49
I'm closing this out because I specifically say that BSD make is required.  The alternative is to unroll all possible regression tests in the Makefile, which are what the BSD extensions (or GNU make extensions) are used for, and that would be a PITA.  So it's either one or the other, I'm afraid!

**Closed by kristapsdz** 2019-07-05 14:49 UTC
